/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.70
 * Generated at: 2023-01-11 07:42:52 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.common;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class header_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(5);
    _jspx_dependants.put("jar:file:/C:/ThisIsJavaSecondEdition/eclipse-workspace/project3_team3/apache-tomcat-9_0_70/wtpwebapps/OOTD-main/WEB-INF/lib/jstl-1.2.jar!/META-INF/fmt.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1626669628000L));
    _jspx_dependants.put("jar:file:/C:/ThisIsJavaSecondEdition/eclipse-workspace/project3_team3/apache-tomcat-9_0_70/wtpwebapps/OOTD-main/WEB-INF/lib/jstl-1.2.jar!/META-INF/fn.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/views/common/../member/loginModal.jsp", Long.valueOf(1626669628000L));
    _jspx_dependants.put("jar:file:/C:/ThisIsJavaSecondEdition/eclipse-workspace/project3_team3/apache-tomcat-9_0_70/wtpwebapps/OOTD-main/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("    ");
      out.write("\n");
      out.write("    <!-- Bootstrap CSS -->\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css\"\n");
      out.write("        integrity=\"sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l\" crossorigin=\"anonymous\">\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js\" integrity=\"sha384-Piv4xVNRyMGpqkS2by6br4gNJ7DXjqk09RmUpJ8jgGtD7zP9yug3goQfGII0yAns\" crossorigin=\"anonymous\"></script>\n");
      out.write("    <script src=\"https://developers.kakao.com/sdk/js/kakao.min.js\"></script>\n");
      out.write("    <script src=\"https://apis.google.com/js/platform.js?onload=init\" async defer></script>\n");
      out.write("    <!-- css 링크 -->\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/loginModal.css\" />\n");
      out.write("\n");
      out.write("    <div class=\"container\">\n");
      out.write("       \n");
      out.write("       ");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("       \n");
      out.write("      ");
      if (_jspx_meth_c_005fif_005f3(_jspx_page_context))
        return;
      out.write("\n");
      out.write("        \n");
      out.write("      </div>\n");
      out.write("\n");
      out.write("      <!-- 아이디 찾기 Modal -->\n");
      out.write("      <div class=\"modal modal-center fade\" id=\"findIdModal\" role=\"dialog\">\n");
      out.write("        <div class=\"modal-dialog\">\n");
      out.write("      \n");
      out.write("            <!-- Modal content-->\n");
      out.write("            <div class=\"modal-content\">\n");
      out.write("                <button type=\"button\" class=\"close\" data-dismiss=\"modal\">&times;</button>\n");
      out.write("                <h3>아이디 찾기</h3>\n");
      out.write("\n");
      out.write("                <div class=\"modal-body\" style=\"padding:40px 50px;\">\n");
      out.write("                    <form role=\"form\" action=\"member/sendIdMail.do\" method=\"post\">\n");
      out.write("                    	\n");
      out.write("                    	<label for=\"brand\" style=\"margin-top:5%\">\n");
      out.write("                    		<input type=\"checkbox\" name=\"login_type\" value=\"1\" checked=\"true\">업체 &nbsp;\n");
      out.write("                    	</label>\n");
      out.write("            			<input type=\"checkbox\" name=\"login_type\" value=\"2\">개인\n");
      out.write("                    	<br /><br />\n");
      out.write("                        <label for=\"username\">이름 / 브랜드 이름</label>\n");
      out.write("                        <div class=\"input-group\">\n");
      out.write("                            <input type=\"text\" name=\"member_name\" class=\"form-control\" id=\"usrname\" placeholder=\"Enter name\">\n");
      out.write("                        </div>\n");
      out.write("\n");
      out.write("                        <label for=\"psw\" style=\"margin-top:5%\">이메일</label>\n");
      out.write("                        <div class=\"input-group\">\n");
      out.write("                            <input type=\"text\" name=\"email\" class=\"form-control\" id=\"psw\" placeholder=\"Enter email\">\n");
      out.write("                        </div>\n");
      out.write("                        <button type=\"submit\" class=\"btn btn-secondary btn-lg btn-block\" style=\"margin-top: 25%;\">아이디 찾기</button>\n");
      out.write("                    </form>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </div> \n");
      out.write("    \n");
      out.write("    \n");
      out.write("\n");
      out.write("      <!-- 비밀번호 찾기 Modal -->\n");
      out.write("      <div class=\"modal modal-center fade\" id=\"findPwModal\" role=\"dialog\">\n");
      out.write("        <div class=\"modal-dialog\">\n");
      out.write("      \n");
      out.write("            <!-- Modal content-->\n");
      out.write("            <div class=\"modal-content\">\n");
      out.write("\n");
      out.write("                <button type=\"button\" class=\"close\" data-dismiss=\"modal\">&times;</button>\n");
      out.write("                <h3>비밀번호 찾기</h3>\n");
      out.write("\n");
      out.write("                <div class=\"modal-body\" style=\"padding:40px 50px;\">\n");
      out.write("                    <form role=\"form\" action=\"member/sendPwMail.do\" method=\"post\">\n");
      out.write("                    	\n");
      out.write("                    	\n");
      out.write("                    	<label for=\"brand\" style=\"margin-top:5%\">\n");
      out.write("                    		<input type=\"checkbox\" name=\"login_type\" value=\"1\" checked=\"true\">업체 &nbsp;\n");
      out.write("                    	</label>\n");
      out.write("            			<input type=\"checkbox\" name=\"login_type\" value=\"2\">개인\n");
      out.write("                    	<br /><br />\n");
      out.write("                        \n");
      out.write("                        <label for=\"username\">아이디</label>\n");
      out.write("                        <div class=\"input-group\">\n");
      out.write("                            <input type=\"text\" name=\"member_id\" class=\"form-control\" id=\"usrname\" placeholder=\"Enter ID\">\n");
      out.write("                        </div>\n");
      out.write("\n");
      out.write("                        <label for=\"username\" style=\"margin-top:5%\">이름 / 브랜드 이름</label>\n");
      out.write("                        <div class=\"input-group\">\n");
      out.write("                            <input type=\"text\" name=\"member_name\" class=\"form-control\" id=\"usrname\" placeholder=\"Enter name\">\n");
      out.write("                        </div>\n");
      out.write("\n");
      out.write("                        <label for=\"psw\" style=\"margin-top:5%\">이메일</label>\n");
      out.write("                        <div class=\"input-group\">\n");
      out.write("                            <input type=\"text\" name=\"email\" class=\"form-control\" id=\"psw\" placeholder=\"Enter email\">\n");
      out.write("                        </div>\n");
      out.write("                        <button type=\"submit\" class=\"btn btn-secondary btn-lg btn-block\" style=\"margin-top: 10%;\">비밀번호 찾기</button>\n");
      out.write("                    </form>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </div> \n");
      out.write("    <script>\n");
      out.write("        /* 버튼 클릭 시, 모달 pop-up */\n");
      out.write("        $(\"#loginBtn\").click(function(){\n");
      out.write("                $(\"#loginModal\").modal();\n");
      out.write("          });\n");
      out.write("\n");
      out.write("        /* 모달 밖의 영역 클릭 시, 모달이 닫히는 것을 방지 */\n");
      out.write("   		//   $('#loginModal').modal({backdrop: 'static', keyboard: false}) ;\n");
      out.write("\n");
      out.write("        /* 모달 내 JOIN 버튼 클릭 시, 회원가입 페이지로 이동 */\n");
      out.write("        function goJoinPage() {\n");
      out.write("        	location.href='");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/member/joinAccept.do';\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        function goMyPage() {\n");
      out.write("        	location.href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/member/goMyPage.do\"\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        function logout() {\n");
      out.write("        	location.href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/member/logout.do\"\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        \n");
      out.write("        /* componentDidMount() {\n");
      out.write("        	Kakao.init('1da952139d172c0ac2c48f4a3ba9ca34');\n");
      out.write("        } */\n");
      out.write("        \n");
      out.write("        var code = $('#kakaoCode').val();\n");
      out.write("        console.log(code);\n");
      out.write("        var tocken;\n");
      out.write("        \n");
      out.write("        $(function() {\n");
      out.write("        	Kakao.init('1da952139d172c0ac2c48f4a3ba9ca34');\n");
      out.write("        	// SDK 초기화 여부를 판단합니다.\n");
      out.write("            console.log(Kakao.isInitialized());\n");
      out.write("        	\n");
      out.write("        });\n");
      out.write("        \n");
      out.write("        $('#kakao-box').on('click', function() {\n");
      out.write("        	loginWithKakao();\n");
      out.write("        	\n");
      out.write("        });\n");
      out.write("        \n");
      out.write("        $('#google-box').on('click', function() {\n");
      out.write("        	onSignIn();\n");
      out.write("        }); \n");
      out.write("        \n");
      out.write("        \n");
      out.write("        \n");
      out.write("        //카카오 로그인\n");
      out.write("        function loginWithKakao() {	\n");
      out.write("              \n");
      out.write("        	Kakao.Auth.login({\n");
      out.write("            	success: function (response) {\n");
      out.write("            	    Kakao.API.request({\n");
      out.write("            	        url: '/v2/user/me',\n");
      out.write("            	        success: function (response) {\n");
      out.write("            	        	console.log(response)\n");
      out.write("            	        	console.log(response.id)\n");
      out.write("            	        	console.log(response['kakao_account']['profile']['nickname'])\n");
      out.write("            	        	  \n");
      out.write("            	        	var id = response.id;\n");
      out.write("            	        	var name = response['kakao_account']['profile']['nickname'];\n");
      out.write("            	            var email = response['kakao_account']['email'];\n");
      out.write("            	        	  \n");
      out.write("            	            kakaoLogout();\n");
      out.write("            	        	  \n");
      out.write("            	        	$.ajax({\n");
      out.write("            	      			type: \"POST\",\n");
      out.write("            	      			url: \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/member/emailCheck.do\",\n");
      out.write("            	      			data: { email : email }, \n");
      out.write("            	      			success: function(data){\n");
      out.write("            	      				console.log(data);\n");
      out.write("            	      				console.log(\"Kakao email 검사 성공\")\n");
      out.write("            	      				\n");
      out.write("            	      				\n");
      out.write("            	      				\n");
      out.write("            	      				if ( data == \"\" ) {\n");
      out.write("	      								location.href = '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/member/snsMemberJoin.do?member_id='+id+'&email='+email+'&name='+name;\n");
      out.write("	      							} else {\n");
      out.write("	      								\n");
      out.write("	      								if ( data == id ) {\n");
      out.write("	      									location.href = '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/member/snsLogin.do?member_id='+id;\n");
      out.write("	      								} else {\n");
      out.write("	      									alert(\"이미 해당 이메일로 가입되어 있는 계정이 존재합니다. 아이디 찾기를 이용해 내일의 옷 계정으로 로그인해주세요.\");\n");
      out.write("	      								}\n");
      out.write("	      					\n");
      out.write("	      				}\n");
      out.write("            	      				\n");
      out.write("            	      			},\n");
      out.write("            	      			\n");
      out.write("            	      			error: function(){\n");
      out.write("            	      				alert('Kakao email 검사 실패');\n");
      out.write("            	      			}\n");
      out.write("            	      			\n");
      out.write("            	      		});\n");
      out.write("            	          },\n");
      out.write("            	          \n");
      out.write("            	          fail: function (error) {\n");
      out.write("            	            console.log(error)\n");
      out.write("            	          },\n");
      out.write("            	        })\n");
      out.write("            	      },\n");
      out.write("            	      fail: function (error) {\n");
      out.write("            	        console.log(error)\n");
      out.write("            	      },\n");
      out.write("            	    })\n");
      out.write("            	  \n");
      out.write("          }\n");
      out.write("        \n");
      out.write("        function kakaoLogout() {\n");
      out.write("            if (Kakao.Auth.getAccessToken()) {\n");
      out.write("              Kakao.API.request({\n");
      out.write("                url: '/v1/user/unlink',\n");
      out.write("                success: function (response) {\n");
      out.write("                	console.log(response)\n");
      out.write("                },\n");
      out.write("                fail: function (error) {\n");
      out.write("                  console.log(error)\n");
      out.write("                },\n");
      out.write("              })\n");
      out.write("              Kakao.Auth.setAccessToken(undefined)\n");
      out.write("            }\n");
      out.write("          }  \n");
      out.write("\n");
      out.write("      // google login 처음 실행하는 함수\n");
      out.write("          function init() {\n");
      out.write("        	gapi.load('auth2', function() { \n");
      out.write("        		gapi.auth2.init();\n");
      out.write("        		options = new gapi.auth2.SigninOptionsBuilder();\n");
      out.write("        		options.setPrompt('select_account');\n");
      out.write("                // 추가는 Oauth 승인 권한 추가 후 띄어쓰기 기준으로 추가\n");
      out.write("        		options.setScope('email profile openid https://www.googleapis.com/auth/userinfo.profile');\n");
      out.write("                // 인스턴스의 함수 호출 - element에 로그인 기능 추가\n");
      out.write("                // GgCustomLogin은 li태그안에 있는 ID, 위에 설정한 options와 아래 성공,실패시 실행하는 함수들\n");
      out.write("        		gapi.auth2.getAuthInstance().attachClickHandler('GgCustomLogin', options, onSignIn, onSignInFailure);\n");
      out.write("        	})\n");
      out.write("        } \n");
      out.write("\n");
      out.write("       \n");
      out.write("        // 구글구글구글구글\n");
      out.write("        function onSignIn(googleUser) {\n");
      out.write("        	 var profile = googleUser.getBasicProfile();\n");
      out.write("        	 console.log('ID: ' + profile.getId()); // Do not send to your backend! Use an ID token instead.\n");
      out.write("        	 console.log('Name: ' + profile.getName());\n");
      out.write("        	 console.log('Email: ' + profile.getEmail()); // This is null if the 'email' scope is not present.\n");
      out.write("        	 var id = profile.getId();\n");
      out.write("        	 var name = profile.getName();\n");
      out.write("        	 var email = profile.getEmail();\n");
      out.write("        	 \n");
      out.write("        	 signOut();\n");
      out.write("        	 \n");
      out.write("        	 $.ajax({\n");
      out.write("       			type: \"POST\",\n");
      out.write("       			url: \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/member/emailCheck.do\",\n");
      out.write("       			data: { email : email }, \n");
      out.write("       			success: function(data){\n");
      out.write("       				console.log(data);\n");
      out.write("       				console.log(\"Google email 검사 성공\");\n");
      out.write("       				\n");
      out.write("       				if ( data == \"\" ) {\n");
      out.write("       					location.href = '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/member/snsMemberJoin.do?member_id='+id+'&email='+email+'&name='+name;\n");
      out.write("       				} else {\n");
      out.write("       					if ( data == id ) {\n");
      out.write("       						location.href = '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/member/snsLogin.do?member_id='+id;\n");
      out.write("       						\n");
      out.write("       					} else {\n");
      out.write("       						alert(\"이미 해당 이메일로 가입되어 있는 계정이 존재합니다. 아이디 찾기를 이용해 내일의 옷 계정으로 로그인해주세요.\");\n");
      out.write("       					}\n");
      out.write("       					\n");
      out.write("       				}\n");
      out.write("       				\n");
      out.write("       			},\n");
      out.write("       			\n");
      out.write("       			error: function(){\n");
      out.write("       				alert('Google email 검사 실패');\n");
      out.write("       			}\n");
      out.write("       			\n");
      out.write("       		});\n");
      out.write("        	 \n");
      out.write("        }\n");
      out.write("      \n");
      out.write("        \n");
      out.write("        function signOut() {\n");
      out.write("            var auth2 = gapi.auth2.getAuthInstance();\n");
      out.write("            auth2.signOut().then(function () {\n");
      out.write("              console.log('User signed out.');\n");
      out.write("            });\n");
      out.write("          }\n");
      out.write("        \n");
      out.write("        function onSignInFailure(t){		\n");
      out.write("        	console.log(t);\n");
      out.write("        }\n");
      out.write("        	\n");
      out.write("        \n");
      out.write("        \n");
      out.write("    </script>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("	<header class=\"header\">\n");
      out.write("		<div class=\"header_nav\">\n");
      out.write("			<!-- HEADER 로고 클릭 시 index화면으로 이동 -->\n");
      out.write("			<div class=\"header_logo\">\n");
      out.write("				<img\n");
      out.write("					src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/headerlogo.png\"\n");
      out.write("					id=\"logo\" />\n");
      out.write("			</div>\n");
      out.write("\n");
      out.write("			<!-- Header Brand, Second Hands (클릭 시 하단에 메뉴바) -->\n");
      out.write("			<div class=\"header_menu\">\n");
      out.write("				<div>\n");
      out.write("					<h3 id=\"brand\">BRAND</h3>\n");
      out.write("				</div>\n");
      out.write("				<div>\n");
      out.write("					<h3 id=\"second_Hand\">SECOND HAND</h3>\n");
      out.write("				</div>\n");
      out.write("			</div>\n");
      out.write("\n");
      out.write("			<!-- 검색창, 장바구니, 마이페이지, 다크모드 -->\n");
      out.write("			<div class=\"header_option\">\n");
      out.write("				<ul class=\"nav_menu\">\n");
      out.write("					<li class=\"search_li\">\n");
      out.write("						<div>\n");
      out.write("\n");
      out.write("							<form action=\"/header/totalSearch.do\" method=\"POST\" id=\"search_main\">\n");
      out.write("								<input type=\"text\" class=\"search_input\" name=\"totalSearch\"><i class=\"fas fa-search fa-lg\"></i>\n");
      out.write("							</form>\n");
      out.write("						</div>\n");
      out.write("\n");
      out.write("					</li>\n");
      out.write("\n");
      out.write("					<li><i class=\"fas fa-shopping-cart fa-lg\" id=\"cartIcon\"></i></li>\n");
      out.write("\n");
      out.write("					<li><i class=\"fas fa-user fa-lg\" id=\"loginBtn\"\n");
      out.write("						data-target=\"#loginModal\" data-toggle=\"modal\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextContext.request.contextPage }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/views/myPage/myPage_Info.jsp\"></i></li>\n");
      out.write("					<li>\n");
      out.write("						<span class=\"fa-stack fa-lg\"> \n");
      out.write("							<i class=\"far fa-sun fa-stack-1x fa-lg\"></i> \n");
      out.write("							<i class =\"far fa-moon fa-stack-1xfa-lg\"></i>\n");
      out.write("						</span>\n");
      out.write("					</li>\n");
      out.write("\n");
      out.write("				</ul>\n");
      out.write("\n");
      out.write("\n");
      out.write("			</div>\n");
      out.write("		</div>\n");
      out.write("	</header>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("	<script>\n");
      out.write("	\n");
      out.write("	$(function() {		\n");
      out.write("		$('#brand').on('click', function() {\n");
      out.write("			\n");
      out.write("			var pType = 1;\n");
      out.write("			location.href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/product/productList.do?pType=\"+pType;\n");
      out.write("		});\n");
      out.write("	});\n");
      out.write("	\n");
      out.write("	$(function() {		\n");
      out.write("		$('#second_Hand').on('click', function() {\n");
      out.write("			\n");
      out.write("			var pType = 2;\n");
      out.write("			location.href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/product/productList.do?pType=\"+pType;\n");
      out.write("		});\n");
      out.write("	});\n");
      out.write("	\n");
      out.write("	\n");
      out.write("	\n");
      out.write("	\n");
      out.write("	\n");
      out.write("		$(function() {\n");
      out.write("\n");
      out.write("			var icon = document.getElementById(\"logo\");\n");
      out.write("			var icon_footer = document.getElementById(\"logo_footer\")\n");
      out.write("			\n");
      out.write("			$('ul').children('li').find('.fa-search').click(function() {\n");
      out.write("				if ($('.search_input').val() != \"\") { \n");
      out.write("					location.href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/header/totalSearch.do?totalSearch=\" + $('.search_input').val();\n");
      out.write("				} else if($('.search_input').val() == \"\") {\n");
      out.write("					alert(\"원하시는 상품명 또는 브랜드명을 입력해주세요.\");\n");
      out.write("					$('#search_main').attr('disabled');\n");
      out.write("				}\n");
      out.write("			})\n");
      out.write("\n");
      out.write("			//  $('ul').children('li').find('.fa-user').click(function() {\n");
      out.write("			//       alert(\"로그인 되있으면 마이페이지 안되있으면 로그인 페이지\");\n");
      out.write("			//  })\n");
      out.write("			\n");
      out.write("			$('.fa-moon').on('click', function() {\n");
      out.write("				\n");
      out.write("				$('html').toggleClass(\"dark\");\n");
      out.write("		        var mode = $('html').attr('class');\n");
      out.write("		        localStorage.setItem('darkMode', mode)\n");
      out.write("		        \n");
      out.write("		        $('.search_input').css('background-color','black');\n");
      out.write("				$('.search_input').css('color', 'white');\n");
      out.write("				$('.myPageInfo').css('text-decoration', 'none');\n");
      out.write("				$('.myPageInfo').css('color', '#bbb');\n");
      out.write("				$('.bx-wrapper').css('background-color', 'black');\n");
      out.write("				\n");
      out.write("				icon.src = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/headerdarklogo.png\";\n");
      out.write("				icon_footer.src = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/footerdarklogo.jpeg\";\n");
      out.write("				\n");
      out.write("				$('.fa-moon').hide();\n");
      out.write("				$('.fa-sun').css('visibility', 'visible');\n");
      out.write("		        \n");
      out.write("			});\n");
      out.write("\n");
      out.write("							\n");
      out.write("\n");
      out.write("			$('.fa-sun').on('click', function() {\n");
      out.write("				$('html').toggleClass(\"dark\");\n");
      out.write("		        var mode = $('html').attr('class');\n");
      out.write("		        localStorage.setItem('darkMode', mode);\n");
      out.write("		        \n");
      out.write("		        $('.search_input').css('background-color','white');\n");
      out.write("				$('.search_input').css('color', '#bbb');\n");
      out.write("				$('.myPageInfo').css('text-decoration', 'none');\n");
      out.write("				$('.myPageInfo').css('color', 'black');\n");
      out.write("				$('.bx-wrapper').css('background-color', 'white');\n");
      out.write("\n");
      out.write("				icon.src = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/headerlogo.png\";\n");
      out.write("				icon_footer.src = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/footerlogo.png\";\n");
      out.write("				\n");
      out.write("				$('.fa-sun').css('visibility', 'hidden');\n");
      out.write("				$('.fa-moon').show();\n");
      out.write("		        \n");
      out.write("			});\n");
      out.write("\n");
      out.write("			$('.header_logo').on('click', function() {\n");
      out.write("\n");
      out.write("				location.href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/\";\n");
      out.write("\n");
      out.write("			})\n");
      out.write("\n");
      out.write("		});\n");
      out.write("		\n");
      out.write("	// 카트 아이콘 클릭시 장바구니 이동\n");
      out.write("	$(\".fa-shopping-cart\").click(function(){\n");
      out.write("		if(");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${empty member}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("){\n");
      out.write("			alert(\"회원 전용 기능입니다.\")\n");
      out.write("		}else{\n");
      out.write("			location.href = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/order/cart.or\";\n");
      out.write("		}\n");
      out.write("	});\n");
      out.write("	\n");
      out.write("	// localStorage에 담긴 darkMode 여부에 따라서 html 에 class 주기\n");
      out.write("	$(function() {\n");
      out.write("		\n");
      out.write("		var icon = document.getElementById(\"logo\");\n");
      out.write("		var icon_footer = document.getElementById(\"logo_footer\")\n");
      out.write("		\n");
      out.write("        console.log(localStorage.getItem('darkMode'));\n");
      out.write("        $('html').attr('class', localStorage.getItem('darkMode'));\n");
      out.write("        \n");
      out.write("        if( $('html').attr('class') == 'dark' ) {\n");
      out.write("        	\n");
      out.write("        	$('.search_input').css('background-color','black');\n");
      out.write("			$('.search_input').css('color', 'white');\n");
      out.write("\n");
      out.write("			icon.src = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/headerdarklogo.png\";\n");
      out.write("			icon_footer.src = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/footerdarklogo.jpeg\";\n");
      out.write("			\n");
      out.write("			$('.fa-moon').hide();\n");
      out.write("			$('.fa-sun').css('visibility', 'visible');\n");
      out.write("        	\n");
      out.write("        } else {\n");
      out.write("        	\n");
      out.write("        	$('.search_input').css('background-color','white');\n");
      out.write("			$('.search_input').css('color', '#bbb');\n");
      out.write("\n");
      out.write("			icon.src = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/headerlogo.png\";\n");
      out.write("			icon_footer.src = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/footerlogo.png\";\n");
      out.write("			$('.fa-sun').css('visibility', 'hidden');\n");
      out.write("			$('.fa-moon').show();\n");
      out.write("        	\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("    });\n");
      out.write("	\n");
      out.write("	\n");
      out.write("	</script>\n");
      out.write("\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /WEB-INF/views/common/../member/loginModal.jsp(19,7) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ !empty member }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("       \n");
          out.write("       <!-- 내 정보 Modal -->\n");
          out.write("       <div class=\"modal modal-center fade\" id=\"loginModal\" role=\"dialog\" data-backdrop=\"static\" data-keyboard=\"false\">\n");
          out.write("          <div class=\"modal-dialog\"> \n");
          out.write("          \n");
          out.write("            <!-- Modal 컨텐츠 시작 -->\n");
          out.write("            <div class=\"modal-content\">\n");
          out.write("                <button type=\"button\" class=\"close\" data-dismiss=\"modal\">&times;</button>\n");
          out.write("                \n");
          out.write("                ");
          if (_jspx_meth_c_005fif_005f1(_jspx_th_c_005fif_005f0, _jspx_page_context))
            return true;
          out.write("\n");
          out.write("                \n");
          out.write("                ");
          if (_jspx_meth_c_005fif_005f2(_jspx_th_c_005fif_005f0, _jspx_page_context))
            return true;
          out.write("\n");
          out.write("                \n");
          out.write("                <!-- Modal 내 ID/PW 입력 및 로그인/ 가입 버튼 시작 -->\n");
          out.write("                <div class=\"modal-body\" style=\"padding:40px 50px;\">\n");
          out.write("                    <div class=\"join-btn-group\">\n");
          out.write("                        <button type=\"button\" id=\"join-btn\" class=\"btn btn-link\" onclick=\"goMyPage()\">MYPAGE</button>\n");
          out.write("                            | \n");
          out.write("				    	<button type=\"button\" id=\"logout-btn\" class=\"btn btn-link\" onclick=\"logout()\" style=\"color: black; font-size: 20px;\">LOGOUT</button>\n");
          out.write("					</div>\n");
          out.write("                </div> \n");
          out.write("                <!-- 내 정보 모달 끝 -->\n");
          out.write("\n");
          out.write("            </div> \n");
          out.write("            <!-- Modal 컨텐츠 끝 -->\n");
          out.write("\n");
          out.write("         </div>\n");
          out.write("        </div> \n");
          out.write("       \n");
          out.write("       ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f1_reused = false;
    try {
      _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f0);
      // /WEB-INF/views/common/../member/loginModal.jsp(29,16) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ member.login_type == 1 }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
      if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("                <h4 id=\"modal-title\">");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ member.brand_name }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</h4> \n");
          out.write("                ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
      _jspx_th_c_005fif_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f2(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f2 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f2_reused = false;
    try {
      _jspx_th_c_005fif_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f2.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f0);
      // /WEB-INF/views/common/../member/loginModal.jsp(33,16) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f2.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ member.login_type == 2 }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f2 = _jspx_th_c_005fif_005f2.doStartTag();
      if (_jspx_eval_c_005fif_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("                <h4 id=\"modal-title\">");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ member.member_name }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</h4> \n");
          out.write("                ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f2.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f2);
      _jspx_th_c_005fif_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f3(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f3 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f3_reused = false;
    try {
      _jspx_th_c_005fif_005f3.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f3.setParent(null);
      // /WEB-INF/views/common/../member/loginModal.jsp(55,6) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f3.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ empty member }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f3 = _jspx_th_c_005fif_005f3.doStartTag();
      if (_jspx_eval_c_005fif_005f3 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("        <!-- 로그인 Modal -->\n");
          out.write("        <div class=\"modal modal-center fade\" id=\"loginModal\" role=\"dialog\" data-backdrop=\"static\" data-keyboard=\"false\">\n");
          out.write("          <div class=\"modal-dialog\">\n");
          out.write("          \n");
          out.write("            <!-- Modal 컨텐츠 시작 -->\n");
          out.write("            <div class=\"modal-content\">\n");
          out.write("                <button type=\"button\" class=\"close\" data-dismiss=\"modal\">&times;</button>\n");
          out.write("                <h4 id=\"modal-title\">LOGIN</h4>\n");
          out.write("                \n");
          out.write("                <!-- Modal 내 ID/PW 입력 및 로그인/ 가입 버튼 시작 -->\n");
          out.write("                <div class=\"modal-body\" style=\"padding:40px 50px;\">\n");
          out.write("                    <form role=\"form\" action=\"member/memberLogin.do\" method=\"post\">\n");
          out.write("                        <div class=\"form-group\">\n");
          out.write("                            <label for=\"usrname\"> ID</label>\n");
          out.write("                            <input type=\"text\" class=\"form-control\" id=\"member_id\" name=\"member_id\" placeholder=\"Enter ID\">\n");
          out.write("                        </div>\n");
          out.write("                        <div class=\"form-group\">\n");
          out.write("                            <label for=\"psw\"> Password</label>\n");
          out.write("                            <input type=\"password\" class=\"form-control\" id=\"member_pw\" name=\"member_pw\"placeholder=\"Enter password\">\n");
          out.write("                        </div>\n");
          out.write("\n");
          out.write("                        <div class=\"join-btn-group\">\n");
          out.write("                            <button type=\"button\" id=\"join-btn\" class=\"btn btn-link\" onclick=\"goJoinPage()\">JOIN</button>\n");
          out.write("                            |\n");
          out.write("                            <button type=\"submit\" id=\"login-btn\" class=\"btn btn-link\" >LOGIN</button>\n");
          out.write("                        </div>\n");
          out.write("                    </form>\n");
          out.write("                </div>\n");
          out.write("                <!-- Modal 내 ID/PW 입력 및 로그인/ 가입 버튼 끝 -->\n");
          out.write("        \n");
          out.write("\n");
          out.write("              <!-- 모달 내 메신저 ID 로그인 디자인 시작 -->\n");
          out.write("              <div id = \"login-service\">\n");
          out.write("              	<div id=\"kakao-box\">\n");
          out.write("                    <img id=\"icon-img\" src=\"https://t1.daumcdn.net/cfile/tistory/992DA6415B743DB62B\">\n");
          out.write("                    <p id=\"kakao_text\">로그인</p>\n");
          out.write("                </div>\n");
          out.write("                <!-- <div id=\"google-box\">\n");
          out.write("                    <img id=\"icon-img\" src=\"https://t1.daumcdn.net/cfile/tistory/99D8AF415B743DB636\">\n");
          out.write("                    구글로 로그인  -->\n");
          out.write("                    <div class=\"g-signin2\" data-onsuccess=\"onSignIn\"></div>\n");
          out.write("                <!-- </div> -->\n");
          out.write("                ");
          out.write("\n");
          out.write("            </div>\n");
          out.write("            <!-- 메신저 ID 로그인 디자인 끝 -->\n");
          out.write("\n");
          out.write("            <!-- modal의 footer 시작 -->\n");
          out.write("            <div class=\"modal-footer\">\n");
          out.write("                <div class=\"modal-footer-child\">\n");
          out.write("                    Forgot<button type=\"button\" id=\"forgot-id\" class=\"btn btn-link\" data-toggle=\"modal\" data-target=\"#findIdModal\">ID?</button>\n");
          out.write("                    Forgot<button type=\"button\" id=\"forgot-pw\" class=\"btn btn-link\" data-toggle=\"modal\" data-target=\"#findPwModal\">Password?</button>\n");
          out.write("                </div>\n");
          out.write("            </div>\n");
          out.write("            <!-- modal의 footer 끝 -->\n");
          out.write("\n");
          out.write("            </div>\n");
          out.write("            <!-- Modal 컨텐츠 끝 -->\n");
          out.write("\n");
          out.write("          </div>\n");
          out.write("        </div> \n");
          out.write("        \n");
          out.write("        ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f3.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f3);
      _jspx_th_c_005fif_005f3_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f3, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f3_reused);
    }
    return false;
  }
}
